CREATE DATABASE DB_SIEUTHI
GO

USE DB_SIEUTHI
GO

--------------------------------------------------- [ KHỞI TẠO CÁC BẢNG DỮ LIỆU ] ---------------------------------------------------
--------------------- BẢNG QUYỀN TRUY CẬP
CREATE TABLE QUYENTRUYCAP
(
	MAQTC			VARCHAR(10) NOT NULL,
	TENQTC			NVARCHAR(50),
	CONSTRAINT PK_QUYENTRUYCAP PRIMARY KEY(MAQTC)
);

--------------------- BẢNG LOẠI NHÂN VIÊN
CREATE TABLE LOAINHANVIEN
(
	MALNV			VARCHAR(10) NOT NULL,
	TENLNV			NVARCHAR(50),
	MATKHAU			NVARCHAR(6),
	MAQTC			VARCHAR(10) NOT NULL,
	CONSTRAINT PK_LOAINHANVIEN PRIMARY KEY(MALNV)
);

--------------------- BẢNG NHÂN VIÊN
CREATE TABLE NHANVIEN
(
	MANV			VARCHAR(10) NOT NULL,
	HOTEN			NVARCHAR(50),
	ANHDAIDIEN		VARCHAR(100),
	NGAYSINH		DATE,
	GIOITINH		NVARCHAR(5),
	DIACHI			NVARCHAR(100),
	SODIENTHOAI		VARCHAR(10),
	EMAIL			VARCHAR(30),
	MALNV			VARCHAR(10) NOT NULL,
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV)
);

--------------------- BẢNG ĐƠN VỊ TÍNH
CREATE TABLE DONVITINH
(
	MADVT			VARCHAR(10) NOT NULL,
	TENDVT			NVARCHAR(50),
	CONSTRAINT PK_DONVITINH PRIMARY KEY(MADVT)
);

--------------------- BẢNG NHÀ SẢN XUẤT
CREATE TABLE NHASANXUAT
(
	MANSX			VARCHAR(10) NOT NULL,
	TENNXS			NVARCHAR(50),
	DIACHI			NVARCHAR(100),
	SODIENTHOAI		VARCHAR(10),
	CONSTRAINT PK_NHASANXUAT PRIMARY KEY(MANSX)
);

--------------------- BẢNG NHÀ CUNG CẤP
CREATE TABLE NHACUNGCAP
(
	MANCC			VARCHAR(10) NOT NULL,
	TENNCC			NVARCHAR(50),
	DIACHI			NVARCHAR(100),
	SODIENTHOAI		VARCHAR(10),
	CONSTRAINT PK_NHACUNGCAP PRIMARY KEY(MANCC)
);

--------------------- BẢNG SẢN PHẨM
CREATE TABLE SANPHAM
(
	MASP			VARCHAR(10) NOT NULL,
	TENSP			NVARCHAR(50),
	ANHSANPHAM		VARCHAR(100),
	NGAYSX			DATE,
	HANSD			DATE,
	GIASP			DECIMAL(18, 0),
	MOTA			NVARCHAR(100),
	SLTON			INT,
	COKM			BIT,
	MANSX			VARCHAR(10) NOT NULL,
	MANCC			VARCHAR(10) NOT NULL,
	MADVT			VARCHAR(10) NOT NULL,
	CONSTRAINT PK_SANPHAM PRIMARY KEY(MASP)
);

--------------------- BẢNG KHUYẾN MÃI
CREATE TABLE KHUYENMAI
(
	MAKM			VARCHAR(10) NOT NULL,
	TENKM			NVARCHAR(50),
	NGAYBATDAU		DATE,
	NGAYKETTHUC		DATE,
	SOGIAM			VARCHAR(20),
	DIEUKIEN		NVARCHAR(100),
	CONSTRAINT PK_KHUYENMAI PRIMARY KEY(MAKM)
);

--------------------- BẢNG CHI TIẾT KHUYẾN MÃI
CREATE TABLE CHITIETKHUYENMAI
(
	MAKM			VARCHAR(10) NOT NULL,
	MASP			VARCHAR(10) NOT NULL,
	CONSTRAINT PK_CHITIETKHUYENMAI PRIMARY KEY(MAKM, MASP)
);


--------------------- BẢNG VOUCHER
CREATE TABLE VOUCHER
(
	MAVOR			VARCHAR(15) NOT NULL,
	TENVOR			NVARCHAR(50),
	CONHAN			BIT,
	SOGIAM			VARCHAR(20),
	DIEUKIEN		NVARCHAR(100),
	CONSTRAINT PK_VOUCHER PRIMARY KEY(MAVOR)
);

--------------------- BẢNG KHÁCH HÀNG
CREATE TABLE KHACHHANG
(
	MAKH			VARCHAR(10) NOT NULL,
	HOTEN			NVARCHAR(50),
	ANHDAIDIEN		VARCHAR(100),
	NGAYSINH		DATE,
	GIOITINH		NVARCHAR(5),
	DIACHI			NVARCHAR(100),
	SODIENTHOAI		VARCHAR(10),
	MATKHAU			VARCHAR(20),
	EMAIL			VARCHAR(30),
	TINHTHANH		VARCHAR(20),
	DIEMTICHLUY		DECIMAL(5,2),
	CONSTRAINT PK_KHACHHANG PRIMARY KEY(MAKH)
);

--------------------- BẢNG HÓA ĐƠN
CREATE TABLE HOADON
(
	MAHD			VARCHAR(10) NOT NULL,
	NGAYLAP			DATE,
	TONGTIEN		DECIMAL(18, 0),
	THANHTIEN		DECIMAL(18, 0),
	COTICHDIEM		BIT,
	COVOUCHER		BIT,
	CONSTRAINT PK_HOADON PRIMARY KEY(MAHD)
);

--------------------- BẢNG CHI TIẾT VOUCHER
CREATE TABLE CHITIETVOUCHER
(
	MAHD			VARCHAR(10) NOT NULL,
	MAVOR			VARCHAR(15) NOT NULL,
	CONSTRAINT PK_CHITIETVOUCHER PRIMARY KEY(MAHD, MAVOR)
);

--------------------- BẢNG CHI TIẾT HÓA ĐƠN
CREATE TABLE CHITIETHOADON
(
	MAHD			VARCHAR(10) NOT NULL,
	MASP			VARCHAR(10) NOT NULL,
	MANV			VARCHAR(10) NOT NULL,
	SOLUONG			INT,
	MATICHDIEM		VARCHAR(6),
	CONSTRAINT PK_CHITIETHOADON PRIMARY KEY(MAHD)
);

--------------------------------------------------- [ RÀNG BUỘC ] ---------------------------------------------------

--------------------------------------------------------- KHÓA NGOẠI
--------------------- BẢNG LOẠI NHÂN VIÊN
ALTER TABLE LOAINHANVIEN 
ADD CONSTRAINT FK_LOAINHANVIEN_QUYENTRUYCAP FOREIGN KEY(MAQTC) REFERENCES QUYENTRUYCAP(MAQTC)

--------------------- BẢNG NHÂN VIÊN
ALTER TABLE NHANVIEN 
ADD CONSTRAINT FK_NHANVIEN_LOAINHANVIEN FOREIGN KEY(MALNV) REFERENCES LOAINHANVIEN(MALNV)

--------------------- BẢNG SẢN PHẨM
ALTER TABLE SANPHAM
ADD CONSTRAINT FK_SANPHAM_NHASANXUAT FOREIGN KEY(MANSX) REFERENCES NHASANXUAT(MANSX),
	CONSTRAINT FK_SANPHAM_NHACUNGCAP FOREIGN KEY(MANCC) REFERENCES NHACUNGCAP(MANCC),
	CONSTRAINT FK_SANPHAM_DONVITINH FOREIGN KEY(MADVT) REFERENCES DONVITINH(MADVT)

--------------------- BẢNG CHI TIẾT KHUYẾN MÃI
ALTER TABLE CHITIETKHUYENMAI
ADD CONSTRAINT FK_CHITIETKHUYENMAI_SANPHAM FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP),
	CONSTRAINT FK_CHITIETKHUYENMAI_KHUYENMAI FOREIGN KEY(MAKM) REFERENCES KHUYENMAI(MAKM)

--------------------- BẢNG CHI TIẾT VOUCHER
ALTER TABLE CHITIETVOUCHER
ADD CONSTRAINT FK_CHITIETVOUCHER_HOADON FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_CHITIETVOUCHER_VOUCHER FOREIGN KEY(MAVOR) REFERENCES VOUCHER(MAVOR)

--------------------- BẢNG CHI TIẾT HÓA ĐƠN
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CHITIETHOADON_HOADON FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_CHITIETHOADON_SANPHAM FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP),
	CONSTRAINT FK_CHITIETHOADON_NHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)

--------------------------------------------------------- TRIGGER
--------------------- TRIGGER TẠO RANDOM MÃ NHÂN VIÊN
CREATE TRIGGER TAONGAUNHIENMANHANVIEN
ON NHANVIEN
AFTER INSERT
AS
BEGIN    
    UPDATE NHANVIEN
    SET MANV = '#' + LEFT(CAST(ABS(CHECKSUM(NEWID())) AS VARCHAR(10)), 7)
END

--------------------- TRIGGER TẠO RANDOM MÃ KHÁCH HÀNG
CREATE TRIGGER TAONGAUNHIENMAKHACHHANG
ON KHACHHANG
AFTER INSERT
AS
BEGIN    
    UPDATE KHACHHANG
    SET MAKH = '#' + LEFT(CAST(ABS(CHECKSUM(NEWID())) AS VARCHAR(10)), 7)
END