<?xml version="1.0" encoding="utf-8"?><Database Name="DB_SIEUTHI" Class="QLSTDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-QP6JP84;Initial Catalog=DB_SIEUTHI;Persist Security Info=True;User ID=sa" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="DB_SIEUTHIConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETHOADON" Member="CHITIETHOADONs">
    <Type Name="CHITIETHOADON">
      <Column Name="MAHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MATICHDIEM" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="HOADON" ThisKey="MAHD" OtherKey="MAHD" Type="HOADON" IsForeignKey="true" />
      <Association Name="NHANVIEN_CHITIETHOADON" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETHOADON" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VOUCHER" Member="VOUCHERs">
    <Type Name="VOUCHER">
      <Column Name="MAVOR" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENVOR" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CONHAN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SOGIAM" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DIEUKIEN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="VOUCHER_CHITIETVOUCHER" Member="CHITIETVOUCHERs" ThisKey="MAVOR" OtherKey="MAVOR" Type="CHITIETVOUCHER" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETKHUYENMAI" Member="CHITIETKHUYENMAIs">
    <Type Name="CHITIETKHUYENMAI">
      <Column Name="MAKM" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="KHUYENMAI_CHITIETKHUYENMAI" Member="KHUYENMAI" ThisKey="MAKM" OtherKey="MAKM" Type="KHUYENMAI" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETKHUYENMAI" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETVOUCHER" Member="CHITIETVOUCHERs">
    <Type Name="CHITIETVOUCHER">
      <Column Name="MAHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAVOR" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="VOUCHER_CHITIETVOUCHER" Member="VOUCHER" ThisKey="MAVOR" OtherKey="MAVOR" Type="VOUCHER" IsForeignKey="true" />
      <Association Name="HOADON_CHITIETVOUCHER" Member="HOADON" ThisKey="MAHD" OtherKey="MAHD" Type="HOADON" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTLOAISANPHAM" Member="CTLOAISANPHAMs">
    <Type Name="CTLOAISANPHAM">
      <Column Name="MACTLSP" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENCTLSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MALSP" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="CTLOAISANPHAM_SANPHAM" Member="SANPHAMs" ThisKey="MACTLSP" OtherKey="MACTLSP" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.DONVITINH" Member="DONVITINHs">
    <Type Name="DONVITINH">
      <Column Name="MADVT" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDVT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DONVITINH_SANPHAM" Member="SANPHAMs" ThisKey="MADVT" OtherKey="MADVT" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHD" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="COTICHDIEM" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="COVOUCHER" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHOADON" Member="CHITIETHOADON" ThisKey="MAHD" OtherKey="MAHD" Type="CHITIETHOADON" Cardinality="One" />
      <Association Name="HOADON_CHITIETVOUCHER" Member="CHITIETVOUCHERs" ThisKey="MAHD" OtherKey="MAHD" Type="CHITIETVOUCHER" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ANHDAIDIEN" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SODIENTHOAI" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TINHTHANH" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DIEMTICHLUY" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHUYENMAI" Member="KHUYENMAIs">
    <Type Name="KHUYENMAI">
      <Column Name="MAKM" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYBATDAU" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NGAYKETTHUC" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SOGIAM" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DIEUKIEN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="KHUYENMAI_CHITIETKHUYENMAI" Member="CHITIETKHUYENMAIs" ThisKey="MAKM" OtherKey="MAKM" Type="CHITIETKHUYENMAI" />
    </Type>
  </Table>
  <Table Name="dbo.LOAISANPHAM" Member="LOAISANPHAMs">
    <Type Name="LOAISANPHAM">
      <Column Name="MALSP" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHACUNGCAP" Member="NHACUNGCAPs">
    <Type Name="NHACUNGCAP">
      <Column Name="MANCC" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SODIENTHOAI" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Association Name="NHACUNGCAP_SANPHAM" Member="SANPHAMs" ThisKey="MANCC" OtherKey="MANCC" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ANHDAIDIEN" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SODIENTHOAI" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MATK" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Association Name="NHANVIEN_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MANV" OtherKey="MANV" Type="CHITIETHOADON" />
      <Association Name="TAIKHOAN_NHANVIEN" Member="TAIKHOAN" ThisKey="MATK" OtherKey="MATK" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NUOCXUATXU" Member="NUOCXUATXUs">
    <Type Name="NUOCXUATXU">
      <Column Name="MANXX" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNXX" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NUOCXUATXU_SANPHAM" Member="SANPHAMs" ThisKey="MANXX" OtherKey="MANXX" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.QUYENTRUYCAP" Member="QUYENTRUYCAPs">
    <Type Name="QUYENTRUYCAP">
      <Column Name="MAQTC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENQTC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QUYENTRUYCAP_TAIKHOAN" Member="TAIKHOANs" ThisKey="MAQTC" OtherKey="MAQTC" Type="TAIKHOAN" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MASP" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BARCODE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ANHSANPHAM" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NGAYSX" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HANSD" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GIASP" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SLTON" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MANXX" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MANCC" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MADVT" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MACTLSP" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="SANPHAM_CHITIETHOADON" Member="CHITIETHOADONs" ThisKey="MASP" OtherKey="MASP" Type="CHITIETHOADON" />
      <Association Name="SANPHAM_CHITIETKHUYENMAI" Member="CHITIETKHUYENMAIs" ThisKey="MASP" OtherKey="MASP" Type="CHITIETKHUYENMAI" />
      <Association Name="CTLOAISANPHAM_SANPHAM" Member="CTLOAISANPHAM" ThisKey="MACTLSP" OtherKey="MACTLSP" Type="CTLOAISANPHAM" IsForeignKey="true" />
      <Association Name="DONVITINH_SANPHAM" Member="DONVITINH" ThisKey="MADVT" OtherKey="MADVT" Type="DONVITINH" IsForeignKey="true" />
      <Association Name="NHACUNGCAP_SANPHAM" Member="NHACUNGCAP" ThisKey="MANCC" OtherKey="MANCC" Type="NHACUNGCAP" IsForeignKey="true" />
      <Association Name="NUOCXUATXU_SANPHAM" Member="NUOCXUATXU" ThisKey="MANXX" OtherKey="MANXX" Type="NUOCXUATXU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MATK" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="MATKHAU" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="MAQTC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TAIKHOAN_NHANVIEN" Member="NHANVIENs" ThisKey="MATK" OtherKey="MATK" Type="NHANVIEN" />
      <Association Name="QUYENTRUYCAP_TAIKHOAN" Member="QUYENTRUYCAP" ThisKey="MAQTC" OtherKey="MAQTC" Type="QUYENTRUYCAP" IsForeignKey="true" />
    </Type>
  </Table>
</Database>